project:
  type: website

website:
  title: "SMT201-GISProject"
  navbar:
    left:
      - text: Overview
        href: Overview.qmd
      - text: Methodology
        href: Methodology.qmd
      - text: Results and Analysis
        href: Results.qmd
      - text: Interactive map 
        href: "qgis2web/index.html"
      - text: Poster
        href: Poster.qmd
    right:
      - href: index.qmd
        text: Home
      - text: Team
        href: about.qmd
  sidebar: 
    - title: "Methodology"
      style: "docked"
      background: light
      contents:
        - Methodology.qmd
        - Data Source.qmd
        - Data Preparation.qmd
        

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual


