project:
  type: website

website:
  title: "SMT201-GISProject_Group 4"
  navbar:
    left:
      - text: Overview
        href: Overview.qmd
      - text: Methodology
        href: Methodology.qmd
      - text: Results and Discussion
        href: Results.qmd
      - text: Interactive map 
        href: "qgis2web/index.html"
    right:
      - href: index.qmd
        text: Home
      - text: Team
        href: about.qmd

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true

editor: visual

