project:
  type: website

website:
  title: "SMT201-GISProject_Group 3"
  navbar:
    left:
      - text: Overview
        href: Overview.qmd
      - text: Methodology
        href: ""
      - text: Results and Discussion
        href: ""
    right:
      - href: index.qmd
        text: Home
      - text: Team
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

